[pytest]
;全局默认参数（每次运行pytest自动带上-vs）
addopts = -vs
;指定测试用例路径(只扫描tests目录下的文件)
testpaths = .
;指定测试用例文件名匹配规则（必须匹配实际文件名）
python_files = test_*.py
;指定测试用例文件名匹配规则（必须匹配实际函数名）
python_classes = Test*
;指定测试用例方法匹配规则
python_functions = test_*
;注册自定义标记
markers =
    smoke: 冒烟测试用例(核心流程)
    normal: 正常测试用例（功能覆盖）
    exception: 异常测试用例（边界/错误输入）
